#### Numpy

- Pandas : http://pandas.pydata.org/
- Numpy : https://numpy.org/
- 수치해석, 수학적 처리, 통계를 위한 라이브러리(모듈) - Scipy, Pandas, Maploplib

##### Numpy 설치
'''
!pip install numpy
'''


In [1]:
!pip install numpy

In [2]:
!pip install pandas

In [4]:
# import
import pandas as pd
import numpy as np

##### numpy를 쓰는 이유
- python 리스트를 만들고 사용처리 (1,000,000건) - 260ms
- numpy 배열을 만들고 사용처리 (1,000,000건) - 34.3ms(8배 정도 빠름)

In [7]:
py_list =list(range(1_000_000)) # 100만건 리스트 만들기

In [8]:
np_arr = np.arange(1_000_000)

In [10]:
# 파이썬 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2

151 ms ± 1.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
# 넘파이로 리스트 사용
%timeit for _ in range(10) : np_arr2 = np_arr * 2

15.5 ms ± 313 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### 넘파이로 배열 생성. 연산, 등...

- 파이썬 리스트는 +(리스트끼리), *(숫자만) 연산 밖에 없음
- 행렬(백터)로 연산 을 하고 싶으면 numpy 배열로 형변환 후에 처리할 것

In [13]:
# 1차원 배열
np_arr1 =np.array([1, 3, 5])
np_arr1

array([1, 3, 5])

In [16]:
# 2차원 배열
np_arr2 = np.array([[1, 3, 5], [1, 3, 5]])
np_arr2

array([[1, 3, 5],
       [1, 3, 5]])

In [18]:
# 3차원 배열
np_arr3 = np.array([[[0, 2, 4], [8, 10, 12]], [[1, 3, 5], [7,9, 12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [19]:
# 파이썬 기본 리스트(배열)
list1 = [1, 3, 5]
list1

[1, 3, 5]

In [20]:
# [1, 3, 5], [1, 3, 5] 는 튜프로 1차원 배여 ㄹ2개가 만들어짐 # numpy에서는 허용 안됨
# [[1,3,4],[1,3,5]] 2차원배열
list2 = [[1, 3, 5], [1, 3, 5]]
list2

[[1, 3, 5], [1, 3, 5]]

In [21]:
# 길의 4의 1차원 배열을 전부 0으로 채울것
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [24]:
np_arr5 = np.zeros([2,3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np_arr6 = np.empty([2, 3])
np_arr6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# 랜덤은 활용도 있음
np.random.randn(2,3)

array([[ 0.76598803, -0.19523406,  2.26213356],
       [ 0.03342268, -0.77370571,  0.74656609]])

In [37]:
np_arr7 = np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# 파이썬에서 리스트만든 다음에 numpy형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# 연산
np_arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
# 파이썬 리스트는 +(리스트끼리), *(숫자만)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [39]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [40]:
np_arr7 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [41]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [42]:
# 넘파이 배열은 연산
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
# 파이썬은 두 리스트를 연결함
list(range(10)) + list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
# 비교연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [47]:
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [50]:
# 조뢰
np_arr7[1]

1

In [51]:
# 인데스 크기를 벗어나면 IndexError 예외발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [52]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [54]:
list2 =list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
[x for x in range(10) if x < 5] # 리스트 내포

[0, 1, 2, 3, 4]

In [56]:
np_arr7[3:9] #뒤의 인덱스는 항상 -1

array([3, 4, 5, 6, 7, 8])

In [57]:
# 2 차원 배열에서 값 조회
np_arr2[1][2]

5

In [61]:
np_arr2[1,2] = 9
np_arr2

array([[1, 3, 5],
       [1, 3, 9]])

In [60]:
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

##### 속성
-  Shape, dtype, T

In [63]:
# 1차원
np_arr1.shape

(3,)

In [64]:
# 2차원
np_arr2.shape

(2, 3)

In [65]:
np_arr2.dtype

dtype('int32')

In [66]:
# Pivot
np_arr2.T

array([[1, 1],
       [3, 3],
       [5, 9]])

In [67]:
np_arr2.T.shape

(3, 2)

##### 기타 함수

In [68]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np_arr.mean()

499999.5

In [70]:
np_arr8.sum()

45

In [71]:
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [72]:
np_arr9 = np.random.random(10)
np_arr9

array([0.11645328, 0.80904755, 0.80753286, 0.76410774, 0.69395089,
       0.92619588, 0.82028833, 0.84730086, 0.77044286, 0.4327823 ])

In [74]:
# 오름차순 정렬
np_arr9.sort()

In [75]:
np_arr9

array([0.11645328, 0.4327823 , 0.69395089, 0.76410774, 0.77044286,
       0.80753286, 0.80904755, 0.82028833, 0.84730086, 0.92619588])

In [76]:
# 내림 차순 정렬
-np.sort(-np_arr9)

array([0.92619588, 0.84730086, 0.82028833, 0.80904755, 0.80753286,
       0.77044286, 0.76410774, 0.69395089, 0.4327823 , 0.11645328])

##### 테스트용 데이터프레임 예제

In [95]:
# 테스트용 더미데이터프레임 만들기
size = 10
df = pd.DataFrame({
    'class' : [['A', 'B', 'C', 'D', 'F'][np.random.randint(0, 5)] for i in range(0,size)],
    'year' : [np.random.randint(2010, 2024) for i in range(0, size)],
    'month' : [np.random.randint(1, 13) for i in range(0, size)],
    'val1' : [np.random.randint(1,11)for i in range(0, size)],
    'val2' : [np.random.randint(100,1000)for i in range(0, size)],
    'val3' : [np.random.randint(10000,20000)for i in range(0, size)]
}) 

df

class  year  month  val1  val2   val3
0     B  2018      1     9   244  12524
1     A  2013      3     3   677  18171
2     F  2022      8     2   938  14401
3     A  2014      1     2   542  18275
4     A  2020      5     1   292  17155
5     D  2012      8    10   325  18386
6     C  2012      7    10   328  19714
7     F  2010      4     8   913  16786
8     A  2017      7     1   143  14493
9     C  2013     12    10   358  17041

In [96]:
df.shape

(10, 6)

In [97]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [99]:
df.T.shape

(6, 10)